dbs:
  - path: /opt/polymarket-bot/data/bot.db
    replicas:
      - type: s3
        bucket: ${S3_BUCKET}
        path: bot.db

  - path: /opt/polymarket-bot/data/bot_p2.db
    replicas:
      - type: s3
        bucket: ${S3_BUCKET}
        path: bot_p2.db
